services:
  # Backend Service
  - type: web
    name: neurax-gf-backend
    runtime: node
    plan: free
    rootDir: r3f-virtual-girlfriend-backend-main/r3f-virtual-girlfriend-backend-main
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ELEVEN_LABS_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: deepseek/deepseek-r1:free
      - key: ELEVENLABS_VOICE_ID
        value: 21m00Tcm4TlvDq8ikWAM
    healthCheckPath: /health

  # Frontend Service (Static Site)
  - type: static
    name: neurax-gf-frontend
    buildCommand: cd r3f-virtual-girlfriend-frontend-main/r3f-virtual-girlfriend-frontend-main && npm install && npm run build
    staticPublishPath: r3f-virtual-girlfriend-frontend-main/r3f-virtual-girlfriend-frontend-main/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: neurax-gf-backend
          property: host
